# Generated by Django 5.0.6 on 2024-06-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miaplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=255),
        ),
    ]
